---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3005620076-Ke6e97E9UjQBY9HCUtskQpYqfG5IkdfxIZ2RDs5
:access_token_secret: Vt24cfgy6itLR1vlFiAyToqmCcWBDXPdZL69bi3qgsPkF
